### ISSUE TITLE
wordings of button cannot display properly

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#1]
maxthon:4.4.5.2000

![default](https://cloud.githubusercontent.com/assets/7941949/7883394/ccbfd9a0-0648-11e5-93eb-2fc9d05aa294.png)

**Comment by kliop00023** [comment]
ps thanks for changing to this platform ^o^

**Comment by Deathamns** [comment]
Only those two strings?
What language are you using?
Did you install it from the Maxthon store, or tried to build it from GitHub?

**Comment by kliop00023** [comment]
no, all the strings have problem i think
i'm using english and it does not swap language when i swap the language in the browser
install it from the Maxthon store
![default](https://cloud.githubusercontent.com/assets/7941949/7896829/806a4594-06f8-11e5-9998-960176eb7289.png)

**Comment by Deathamns** [comment]
Seems like I forgot to include all the locale files for Maxthon. I'll re-send it next week (they don't do reviews on weekends).
