### ISSUE TITLE
Viewhance no longer seems to grab local images

### ISSUE THREAD

**Issue by Sappow** [Deathamns/Viewhance#10]
On Chrome, In previous versions this (or possibly Imagus) had an option somewhere to work on (and thus, conveniently center and zoom) image files opened from local storage in the browser; after the updates to the extensions yesterday, that option either got reset and I can't identify how to fix it, or whatever was enabling it was removed.

Currently trying to figure out how to load the previous versions of the extensions from the code, so I can give more useful feedback about the issue I am seeing.

**Comment by Sappow** [comment]
Never mind; problem was resolved after updating chromium itself. Sorry!

**Comment by Deathamns** [comment]
Just for the record, you have to "Allow access to file URLs" on `chrome://extensions/` to make it work on local files.

**Comment by Sappow** [comment]
Yeah, I had that enabled but for some reason chrome wasn't letting it happen until I updated chrome itself.

It is a mystery.
