### ISSUE TITLE
problems with the option "Center content"

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#11]
Maxthon:4.4.7.3000 in 1.03

images especially those are vertical, that is the width is smaller than its height, will have the following problems (the probability is about 1/3 to 1/5, and for horizontal image P(getting issue) is lower;but once it arise, P(getting issue) will be similar):

1. cannot centre properly and will shift to a little bit to right.

2. the icons in the toolbar will shake:
![123](https://cloud.githubusercontent.com/assets/7941949/10043282/5715b19c-6224-11e5-8aa0-94ea65691cd8.gif)

3. the toolbar is larger than normal one like in the images(in scale):
![default](https://cloud.githubusercontent.com/assets/7941949/10043325/bbcf014c-6224-11e5-8b8c-bd47e7c7cebe.png)

settings that you need to follow in order to recreate it:
Initial sizing mode-fit to width
Center content-on

**Comment by Deathamns** [comment]
1. Can't reproduce this one.
2. This is a Maxthon issue, and it happens only when the page is zoomed (I could reproduce it with a 110% or 130% zoomed page).
3. The menu is part of the page, so this is normal. The extension can't tell the difference if the page is zoomed or not (at least I don't know any way).
