### ISSUE TITLE
Integer zoom factors for viewing pixel art

### ISSUE THREAD

**Issue by grompe** [Deathamns/Viewhance#13]
This extension can be more useful for viewing pixel art if zooming was changed by integer factors, for example, 25%, 50%, 100%, 200%, 400%.

Bonus if integer factors above 100% automatically set the image to crisp mode.

**Comment by Deathamns** [comment]
That would require detecting pixel art first, which is probably not easy and inefficient to do for every image.

**Comment by grompe** [comment]
No need to detect anything, if this is default behavior, normal images are viewed just as well or better. I mentioned pixel art because the improvement is most obvious in that use case.

**Comment by ArloJamesBarnes** [comment]
@Deathamns I raised an issue ticket on the Chrome webstore when you were handling support (for Chromium-based browsers, anyway) through there, concerning use of the scaling algorithm used (like @grompe, I was interested in viewing pixel art and continue to be).  
You pointed out to me that the browser handles the scaling, and the only thing Viewhance (or Imagus, for that matter) can do about it is to suggest in the custom CSS field that the browser use nearest neighbor (referred to as something like 'fast, low-quality scaling').  
You even gave some example CSS rules to make this happen, but now that the 'Support' section of the webstore directs users here, I cannot find that relevant comment.

I think that code snippet would address this issues 'bonus' request.

**Comment by Deathamns** [comment]
@ArloJamesBarnes It was [image-rendering](https://developer.mozilla.org/en/docs/Web/CSS/image-rendering). In Viewhance you can change this value on demand with the shortcut `P` to pixelate the image (or back to normal, which doesn't seem to work now).

**Comment by Deathamns** [comment]
Closing, as I don't wish to implement this. The current method works well. If someone wants to pixelate the images, then s/he can use the shortcut `P`.

**Comment by Deathamns** [comment]
This is somewhat possible now with snap points, implemented in 623ebc8.
In the options set "Zoom step; snap points" to `;.25 .5 1 2 4` which matches your example.
