### ISSUE TITLE
Background color always changes to #c3c3c3 even after saving

### ISSUE THREAD

**Issue by minowaeli** [Deathamns/Viewhance#15]
http://i.imgur.com/1Cl6Sha.png

Changing the background color will still be #c3c3c3 even after saving

**Comment by Deathamns** [comment]
That is not for changing the background color, it's just a helper tool to get the color codes, which you could use for the background.

To modify the background color, you have to use CSS (the bigger textarea). The first line in that box tells the color of the background.

```
body { background: silver; overflow: hidden; }
```

You can change the word `silver` to something else. For example `pink` which color code is `#ffaec9`, but any valid value for the CSS `background` property can be used.

**Comment by minowaeli** [comment]
Oh wow, I'm an idiot. Thanks!
