### ISSUE TITLE
Maybe bugs and suggestions for improvement

### ISSUE THREAD

**Issue by led9** [Deathamns/Viewhance#16]
Hello,
Image 5184 x 3888 (5,1 Mb) http://ixbt.photo/photo/1085154/54082xhSZ1Dseao/x0BfwGvFQH/1123318.jpg
not properly zoomed, the white fields visible - 
![1](https://cloud.githubusercontent.com/assets/7848312/15797689/2966930e-2a3a-11e6-9980-41152fe3cdfc.jpg)
it occurs on almost all images larger than the window(i have 4k, browser screen maximized and not - same)

Little bug - 
![2](https://cloud.githubusercontent.com/assets/7848312/15797701/a6e016fc-2a3a-11e6-9378-cbe7d7fa0279.jpg)

This happens in the new version Opera. Opera based on chromium.
The Installation links in blog:
http://www.opera.com/blogs/desktop/2016/06/opera-developer-39-0-2248-0/
Please fix.

Suggestions - 
small images -> fit in window = 
Now you have restriction and the very little image is not stretched to the entire window. Why should this restriction? do please, that certainly worked - 1000 or 50000 percent, does not matter. 

Step of zooming=  
while rotating the mouse wheel the size of image changes with the big jumps. Make zooming smoother, please.

**Comment by led9** [comment]
I install your extension in opera this way =  
"Thanks to this extension you will be able to download and install extensions from Google Chrome Web Store directly in your Opera browser"
https://addons.opera.com/ru/extensions/details/download-chrome-extension-9/?display=en

**Comment by Deathamns** [comment]
1. bug) Can't reproduce.
2. bug) I'll see what can I do about it.

1. suggestion) If you want to upscale small images, then you have to use small percentages.
2. suggestion) I'm satisfied with the current way, I don't intend to change it.

**Comment by led9** [comment]
>bug 1) Can't reproduce.
You install Opera developer-39-0-2248-0, install download-chrome-extension, install your extension and "Can't reproduce."?
I don't think so. 
It's sad, how can you not understand that an error occurs in Opera? I wrote about this 3 times!

**Comment by Deathamns** [comment]
I've tested it on a FullHD monitor, installed the way you described and I don't see any white fields, it works fine.

Are you using default settings?

**Comment by led9** [comment]
Scale of page = 175%, big fonts, other setting default.
I found an extension that works fine (not yours), so you can delete this thread. I was working in the search of extension, and now the search is over.
