### ISSUE TITLE
Images load off screen in Chrome 52

### ISSUE THREAD

**Issue by gilrain** [Deathamns/Viewhance#17]
I run Chrome Beta, and the recent update to Chrome 52 broke Viewhance. Now, images usually (but not always), load in the bottom-right of the screen, and partially off screen. Interestingly, zooming in or out using the Viewhance controls centers the image properly, but returning to default zoom returns it to the off-screen position.

For examples, it's happening for me on [this image](https://321delish.files.wordpress.com/2011/09/ice-cream.jpg), but not on [this image](http://1.bp.blogspot.com/-GGBWTEdu6dk/UIFQAx0jAWI/AAAAAAAAAQs/s4YY7PQuA4U/s1600/ice-cream-1-2.jpg).

**Comment by Deathamns** [comment]
Also reported [here](https://redd.it/4mc799). And fixed in 22f2ed8.

I'll send an update soon if nothing else comes up.
