### ISSUE TITLE
Media Type cannot be determined in newer Chrome versions

### ISSUE THREAD

**Issue by xwcg** [Deathamns/Viewhance#18]
I have been debugging this thing for a bit since it stopped working a while ago, albeit sporadically it still works on some images. It seems that in newer chrome versions, images don't get -webkit- prefixed styles anymore and thus Viewhance fails to determine the media type and consequently the initialization.

I fixed it in a local copy by altering the includes/app.js, changing the selector on line 124 from

    img[style^="-webkit-"]:first-child

to

    img:first-child

**Comment by Deathamns** [comment]
I've just tested with Chrome 53.0.2785.143 m (64-bit), and the structure seems to be the same, and the extension still loads fine.

**Comment by xwcg** [comment]
I just got the update to Version 55.0.2873.0 dev and it seems it was reverted again. I guess it caused problems at other places too, for a while it definitely had the problem though. So I'm closing this again.
