### ISSUE TITLE
Pale Moon 25.5.0 compatibility

### ISSUE THREAD

**Issue by saqq123** [Deathamns/Viewhance#2]
Recent version of Viewhance stopped working with Pale Moon x86 25.5.0 (firefox-based browser), Win 8.1. Extension install just fine but there's no menu on the left side of the screen when viewing image and scroll zoom doesn't work also.

Is there any way to get it to work with PM browser?

Not sure if this is relevant: https://forum.palemoon.org/viewtopic.php?f=5&t=8474

**Comment by Deathamns** [comment]
Fixed in 283e000.

**Comment by Deathamns** [comment]
By the way, I've re-uploaded (and sent to AMO) the fixed version.

**Comment by saqq123** [comment]
Thank you! It works perfectly.
