### ISSUE TITLE
Viewhance not working on Chrome 54

### ISSUE THREAD

**Issue by kyodjinn** [Deathamns/Viewhance#21]
My other laptop is on Chrome 53 and it seems to work. Both are running Viewhance 1.0.9 but the one on Chrome 54 isn't working at all.

**Comment by MangoTangoFox** [comment]
He already fixed it in the newest commit, but he hasn't actually posted the update to the chrome store, nor has he posted the build to his Google Drive with all the old versions. [https://drive.google.com/drive/folders/0Bx8fnUCX4W2IMUpCRWJMMERqV0E]

You can download the source and build it yourself, but I don't know exactly how to do that and would have to install Cygwin to do it. I use Viewhance CONSTANTLY, and it's a massive frustration to have it not work for two weeks, it already be fixed, but no one gives enough of a s##t to spend 20 seconds putting the two pieces together to actually solve the problem. -.-

**Comment by Deathamns** [comment]
It's fixed, however the problem is that I've lost my private key for the extension, and without that I'm not able to publish it on the Chrome Web Store.

**Comment by MangoTangoFox** [comment]
So is uploading a build that we can manually install out too? I'm 100% fine with manually updating, I just want it to work again...

**Comment by Fletchett** [comment]
Hopefully this gets resolved somehow, the extension makes working with images so much easier. :(

**Comment by Deathamns** [comment]
I'll create a new extension with the same name on the Chrome Web Store, and I'll deprecate the current one. Probably in the next couple of days.

**Comment by Jadelor** [comment]
I see you put the new version up in Chrome Web Store already. Thank you very much!
https://chrome.google.com/webstore/detail/viewhance/impppjchnpfgknmbaaghfeopcgfoilac/

**Comment by MangoTangoFox** [comment]
Thank You! It works great again!

Not sure how recent it is, but I noticed the B keybind for changing background color that I hadn't seen before, but it didn't do anything for me, even trying different/no values in the CSS. Shift+B does bring up the text prompt, but editing the RGB values that are there, nor adding hex values worked.

**Comment by Deathamns** [comment]
@Jadelor Yes, that's the [new URL](https://chrome.google.com/webstore/detail/viewhance/impppjchnpfgknmbaaghfeopcgfoilac). As I can't update the extension, I'm not able to notify anyone about the change, so I just put the new link on the old page, and after a while if the number of the users will drop, I'll drop the old version from the Chrome Web Store as well.

@MangoTangoFox Basically it's the same as the old one, except now it works on newer Chrome versions, and it has a different versioning style (UTC date, which I will use from now on).

Also, `B` is not a [new thing](https://github.com/Deathamns/Viewhance/commit/2938066906b956e7d188f852873d15489998b3e1). And it changes the background for transparent images, not the page background. Useful in [situations](http://www.sierravideo.com/media/images/logos/sierra_video_large_logo_horizontal_white_text_tb.png) [like](https://67.media.tumblr.com/8aa076c967f4df14312b6bb44bae1fff/tumblr_nldoa3Bo6Y1u6osmfo1_500.gif) [these](http://i59.tinypic.com/123ppms.png).
