### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by guraga** [Deathamns/Viewhance#23]
Open image in new tab.
Extension not loaded.
Google chrome version 54.0.2840.100 (64-bit).

**Comment by Deathamns** [comment]
Remove the extension and install it from [here](https://chrome.google.com/webstore/detail/impppjchnpfgknmbaaghfeopcgfoilac).

**Comment by inDigazzZ** [comment]
Version 1.0.9 works fine in Chrome 57.0.2942.0, but didn't work in Opera 43.0.2431.0 (and few previous versions).
I've deleted version 1.0.9 and installed 2016.1113.1700, but still doesn't work.

**Comment by Deathamns** [comment]
@inDigazzZ e21a0aa.
