### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by guraga** [Deathamns/Viewhance#24]
* Configurable zoom step.
* Move image using arrow keys.
* Currently top left corner of image can be moved only to top left corner of visible area (for example, can't be placed on center of visible area). Allow move image corners at any location.
* Completely rewrite css of "options.html". Currently "options.html" is not scalable (zoomable).

**Comment by Deathamns** [comment]
1) Maybe, when I got extra time on me.
2) Already possible. Arrow keys, PgUp, PgDown, End, Home
3) I have no intention to implement that.
4) Would be nice, but again, it is time dependent, and it's low priority.

**Comment by Deathamns** [comment]
1. Implemented in 623ebc8, published as v2017.0219.2144.
