### ISSUE TITLE
cannot view this picture when using Viewhance

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#27]
https://github.com/ParticleCore/Particle/raw/gh-pages/images/blue%20glow.png

In fact, all picture in github like this seems down.

Maxthon: 5.0.1.3000

**Comment by Deathamns** [comment]
The browser blocks the image from loading because of [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), however mistakenly. So, this is more like a browser bug, as you can see other browsers can load that image just fine.
