### ISSUE TITLE
Support for .gifv?

### ISSUE THREAD

**Issue by erasedff** [Deathamns/Viewhance#28]
Imgur has quite a lot of gifv files but Viewhance doesn't seem to support this format. I think gifv is pretty much a webm anyway? Since webm is supported by Viewhance, any chance for a gifv support?

**Comment by Deathamns** [comment]
gifv is not a media format, it's just an HTML document which embeds a video file, or a gif (if the browser can't play the video file). Asking support for gifv, is like asking support for a [regular image page](http://imgur.com/gallery/T73ks) on imgur. Viewhance deals with media files that are directly opened in a tab.
