### ISSUE TITLE
[Enhancement] Initial sizing mode's more option

### ISSUE THREAD

**Issue by ldgbc** [Deathamns/Viewhance#29]
Currently the Initial sizing mode have "contain, best fit and standard". From experience I see no different between contain and best fit. Both seem to scale to height. Unless other option where the "?" explain the option in details Initial sizing mode does not.

I would just like to request a "fit to width option", which is currently available as "Left long-press action" but I am requesting if it can be made as an option Initial sizing mode so I dont have to resize it.

**Comment by Deathamns** [comment]
There was option for each to width and to height, but I replaced them with only best fit which makes more sense, as the aspect ratio of the image and the user view-port ratio is always different.

What was your example picture? Fit scales the image to the view-port, so you can see the whole image, best fit scales the image to always fill the view-port, but you don't see the whole image, you have to pan/scroll it to see the rest.

[test1](http://photoblogstop.com/wp-content/uploads/2012/07/Sierra_HDR_Panorama_DFX8048_2280x819_Q40_wm_mini.jpg), [test2](http://kingofwallpapers.com/panorama/panorama-028.jpg).

**Comment by ldgbc** [comment]
Didn't think you reply so fast. I've attached the test image as example. Perhaps I'm just using the wrong setting.

![beg-for-feature-optimized](https://cloud.githubusercontent.com/assets/1805303/25581364/b7142046-2eca-11e7-8554-cf85f38c192c.jpg)

**Comment by Deathamns** [comment]
I've made some changes, do you know how to make builds and test them?

**Comment by Deathamns** [comment]
I think the change worked well enough, so I've published a new version, you don't need to build anything (just wait until it appears in the extension galleries).
