### ISSUE TITLE
report

### ISSUE THREAD

**Issue by FiLinX** [Deathamns/Viewhance#31]
2017.402.1400 version - does not work, crash the browser !!
2017.219.2209 version - works fine!
Win XP3 Pale Moon 26.5.0 https://www.palemoon.org/palemoon-atom.shtml

**Comment by Deathamns** [comment]
Can't confirm. It works fine for me.
Also, if a browser crashes, then always report it to its developers. A browser crash cannot be simply fixed by the extensions.
