### ISSUE TITLE
Checkerboard pattern for transparent images

### ISSUE THREAD

**Issue by Cknight70** [Deathamns/Viewhance#32]
Viewhance has the option of changing the background color of an image with transparency, but has no visible way to make the transparency a checkerboard pattern. I used Viewhance back in 2013 when it was still part of the Imagus extension, and remember the checkerboard pattern being an option. Pretty sure in the form of a dropdown box.
I also remember when the background settings of Viewhance changed to a CSS field with the default color being White (#fafafa) you could still replace it with something like "checkerboard"  and it would show the transparency as a checkerboard pattern. I don't remember what that code was now.

Is there any way to still do this? If so, could it be added to the help tooltip please.

Thanks for the great extension by the way.

**Comment by Deathamns** [comment]
You can use custom CSS, and you can use any value for the background.

For example, append this to your CSS (checkerboard for images):
`img#media { background-image: url("data:image/gif;base64,R0lGODlhFAAUAPABAOjo6P///yH5BAAKAAAALAAAAAAUABQAAAIohI+hy+jAYnhJLnrsxVBP7n1YyHVaSYKhh7Lq+VotPLo1TaW3HEtlAQA7"); }`
