### ISSUE TITLE
Realease Firefox version as webextension

### ISSUE THREAD

**Issue by WyohKnott** [Deathamns/Viewhance#33]
Since you already have the code written fro Chrome, could you release an update for Firefox as a webextension? It's currently maked as a "legacy" extension in Nightly, and these will be shut down in Firefox 57.

**Comment by vlaszlo** [comment]
As of the 2017-08-29 nightly of Firefox the legacy version of Viewhance has stopped working.

**Comment by Deathamns** [comment]
@vlaszlo That's not legacy related, webext would be affected too. Anyway, [fixed](https://github.com/Deathamns/Viewhance/commit/9bde2364c0b44ff4462ca9986aafbeaf2d061840).

**Comment by vlaszlo** [comment]
Oh, OK. Thanks.

**Comment by Deathamns** [comment]
Essentially it's [done](https://github.com/Deathamns/Viewhance/commit/c3f469fb2aae98cdc582452af29a061a445ee80b).

Only [innerHTML](https://github.com/Deathamns/Viewhance/blob/master/platform/crx/js/app.js#L90) needs to be changed somehow to a "safer" method, because AMO won't allow this way.

**Comment by luxoflux** [comment]
To hell with AMO, I compiled it myself and am using it now with Nightly. Works just as good as it always has. Thanks, Deathamns! A must-have extension.

**Comment by Deathamns** [comment]
Published.
