### ISSUE TITLE
[Suggestion] display file size in tab title

### ISSUE THREAD

**Issue by glubsy** [Deathamns/Viewhance#34]
Have you considered adding the size of the opened file in the tab's title as an option?

I was looking into scripting this myself, and I thought it would be a good addition to your extension.

Just started looking into it, and found this project for example: https://github.com/ehaagwlke/View-Image-Info-Chrome/blob/master/js/vii.js

**Comment by ZenFi** [comment]
Rather show it near the image / or with options. Tab bars very cluttered...

**Comment by Deathamns** [comment]
[I've added](https://github.com/Deathamns/Viewhance/commit/9630b095f28ea6ebbd5db1697654e6719b398122) a new `%size` variable, but it may not work in every situation, as there's no reliable way to get the file size. I don't plan to deal with this problem in more detail.

**Comment by glubsy** [comment]
Thank you! That's really awesome. :)
