### ISSUE TITLE
Working in Opera?

### ISSUE THREAD

**Issue by ZenFi** [Deathamns/Viewhance#35]
I'm not really sure if I get this working properly in Opera. 

I don't get the menu such that was pictured in Chrome web store this extension page.

**Comment by Deathamns** [comment]
You have to move your mouse cursor to the top left corner to see the floating menu.

**Comment by ZenFi** [comment]
It works in Opera quite brilliantly. I haven't encountered any bugs.

For usability, I prefer mouse :D

**Comment by ZenFi** [comment]
yeah so I mean Chrome version works wonders in Opera (latest stable 47.x)

and so does Imagus - it's amazing!!! brilliant!

you should upload these, or at least Imagus, to Opera Addon site:  https://addons.opera.com/en/extensions/

**Comment by Deathamns** [comment]
Opera users can install it from the CWS, using [this](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/?display=en) extension. I don't see the reason to upload it to Opera too.

**Comment by EC-O-DE** [comment]
Sure, it's just that Opera (and Vivaldi users might not know of such ext exists (at least consider upping Imagus (it's brilliant))).

Opera and Vivaldi (+ Yandex ext.) users can also DL using this tool: https://addons.opera.com/en/extensions/details/extension-source-viewer/?display=en

It's actually better as one can review the source code before installing (for example to go through http/https in code to see that the ext doesn't send user data to a undisclosed location).
