### ISSUE TITLE
Issue with ViewHance 2017.917.1405 (Webextension)

### ISSUE THREAD

**Issue by mazesy** [Deathamns/Viewhance#36]
Running Viewhance Firefox extension / Waterfox 55.1.0 (built on Firefox 55.0.3) / Windows 7 64-bit

Viewhance / Settings / center content is checked.
ViewHance 2017.917.1405 (Webextension) centers images only, not audio nor video.
Viewhance 2017.502.1705 (legacy add-on) centers all correctly.

I double-checked VH 2017.917.1405 by uninstalling it completely then re-installing it: same issue.
Could be interference with another of my 65 add-ons/webextensions, but no issue with Viewhance 2017.502.1705 (legacy add-on) with which I'll stick for the time being.

**Comment by Deathamns** [comment]
Fixed in d9bb682.
