### ISSUE TITLE
Incorrect height-width ratio when zooming

### ISSUE THREAD

**Issue by dbw9580** [Deathamns/Viewhance#37]
When zooming a picture that is loaded from browser cache (server returned 304 Not Modified), the original height-width ratio of the picture cannot be preserved. This bug also affects rotate and mirror functions, in that a rotation is not done around the centroid of the pic, and mirroring is not done against the middle of the pic. 

If the picture is loaded from the server (initially or via ctrl+F5 force refresh), the bug is not there.

To demonstrate it, I recorded a gif: https://imgur.com/a/Y509K

**Comment by Deathamns** [comment]
You can reproduce this every time? Have you changed some settings? I tried with Firefox 57, but it works as it should.

**Comment by dbw9580** [comment]
No, quite randomly I must say. I just created a fresh Firefox profile and have only Viewhance and User agent Switcher installed and enabled. And open https://www.reddit.com/r/firefox/comments/7f8hbw/webrender_is_amazing/, click on the pic in the topmost post. It would probably work the first time, but after a (few) refresh(es), the bug starts.

I tried disabling User Agent Switcher, this will make the chance smaller, but can't eliminate it.

I also find that pics opened with direct url has a smaller chance hitting the bug, than a pic that is opened from a link in another tab, as the above reddit example.

**Comment by dbw9580** [comment]
Forgot to mention, I'm using FF 57 and Viewhance 2017.917.1405, on Windows 10.

**Comment by dbw9580** [comment]
I only have 'Zoom with mouse wheel' enabled. All other settings are left default.

**Comment by Deathamns** [comment]
I couldn't reproduce it after many attempts. However, switching user agent can be a problem, for example the other open issue is related to the user agent.

**Comment by dbw9580** [comment]
I think I have located the bug: there's a 'height' attribute attached to the img element, forcing the image to be in its initial height when zooming, while the width is changed via inline styles. Deleting the height attribute solves the problem. 

When the bug occurs, there are 'width' and 'height' attributes set to the img element. Remove the 'height' attribute and zooming functions normally. 
![](https://i.imgur.com/k0jY2lc.png)

In other cases, no 'width' and 'height' are set to the element explicitly.
![](https://i.imgur.com/92WTrVU.png)
This screenshot is taken after a force refresh.
Hope this information can be of help.

Sorry I haven't got chrome or other browser to test with. And I think the useragent addon is not the root cause for this, because I also tried installing other addons with viewhance, and it turned out that disabling all the other addons just lowered the chance of the bug, not eliminating it.

**Comment by Deathamns** [comment]
Seems like the extension code initiates before browser code when the image is fetched from cache, because those `class`, `width`, and `height` attributes are from the browser.

**Comment by Deathamns** [comment]
I've sent possible fix, can you build and test it?

**Comment by dbw9580** [comment]
I was unable to either use a proxy file or temporarily load it in a stable release version of Firefox. Stable release doesn't allow unsigned xpi, and load it via about:debugging says `Add-on {00000c4c-fcfd-49bc-9f0d-78db44456c9c} is not compatible with application version. add-on minVersion: 27.0. add-on maxVersion: *.`
I then downloaded the Developer edition, and tried to use the proxy file to install, but it appeared in the legacy extensions section, so still can't get it to work.

**Comment by Deathamns** [comment]
The webextension version for Firefox is the `crx` platform.

**Comment by dbw9580** [comment]
All right, will try again.

**Comment by dbw9580** [comment]
No, the problem persists.

**Comment by Deathamns** [comment]
Try to change [this line](https://github.com/Deathamns/Viewhance/blob/master/src/includes/viewer.js#L1636) to `win.addEventListener('load', onLoad);`, and try then.

**Comment by dbw9580** [comment]
I'm afraid it's still not working.

**Comment by dbw9580** [comment]
When I load the extension from about:debugging the pages says:
```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.
Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.
```
What are these about?

**Comment by Deathamns** [comment]
> What are these about?
Things that are supported in Chrome, but not in Firefox (yet).

Try something else, when you encounter the issue, just resize the window and see if it fixes the problem afterwards.

**Comment by dbw9580** [comment]
Resizing the window does fix the incorrect ratio. But those 3 lines of code doesn't. I've also tried setting a longer timeout value, e.g. 3000, but it makes no difference.

**Comment by Deathamns** [comment]
I've sent a new commit (cb8b3ef), can you try with that?

**Comment by dbw9580** [comment]
Looks good. I am on Firefox 57.0.2 though.

**Comment by Deathamns** [comment]
Did it work in Firefox 57.0.2 correctly without the fix?

**Comment by dbw9580** [comment]
No, the current version from AMO does not work on 57.0.2.

**Comment by Deathamns** [comment]
OK, then we can consider this issue as fixed.
