### ISSUE TITLE
[Feature Request] Open links of Send menu in new tabs

### ISSUE THREAD

**Issue by BobbyWibowo** [Deathamns/Viewhance#38]
I'm referring to the "Send image to..." option. It'd be nice if it was possible to make the links open in new tabs when clicked (and preferably NOT switching the active tab to them).
You'd think that people could just middle-click the link with their mouse to do the same, but that would not really be an option on a laptop without a mouse. Even more so if you'd just want to quickly send the image to 2 or more links.

**Comment by Deathamns** [comment]
You can `Ctrl+Click` or `Ctrl+Shift+Click` in every browser to open links in new tab. I intentionally used normal links there, because this way everyone can decide how they want to open it (and I don't have to implement anything).

**Comment by rawdez** [comment]
or Middle-Mouse-Button click
