### ISSUE TITLE
XUL Gecko Goanna compatibility

### ISSUE THREAD

**Issue by Rimole** [Deathamns/Viewhance#39]
Versions for Firefox newer than viewhance-2017.502.1705-fx+sm.xpi cannot be installed in SeaMonkey or Pale Moon - ok, naturally, as they are for Firefox, but neither are there separates downloads for those browsers. With viewhance-2017.502.1705-fx+sm.xpi in Pale Moon the preferences are not accessible (neither by "image sidebar" nor Add Ons > Options) and the Browser Tabs lose their close buttons and get moved to the right (randomly).
Please create a Pale Moon compatible version, thank you!

**Comment by Deathamns** [comment]
I've just installed the latest version ([`Viewhance.xpi`](https://drive.google.com/drive/folders/0Bx8fnUCX4W2IOTdESEFoM3luS1U)) for PaleMoon and Seamonkey, and it still works fine in both of them.
