### ISSUE TITLE
floating menu icon lost

### ISSUE THREAD

**Issue by seventhsky** [Deathamns/Viewhance#4]
the zoom icon does not show in Firefox 40

**Comment by Deathamns** [comment]
It looks good to me in Nightly (and in other browsers).
Those icons are actually unicode characters, so maybe unicode support is broken at your side.
Probably it would be better to replace them with images/SVGs.

**Comment by seventhsky** [comment]
I test it on Firefox Developer Edition,so I will wait update.
Thank you.

**Comment by Deathamns** [comment]
Fixed in fe1cbec.
