### ISSUE TITLE
size of the menu area

### ISSUE THREAD

**Issue by rawdez** [Deathamns/Viewhance#40]
menu area overlaps with OS taskbar and taskbar appears over menu.
please add option to customize it or simply enlarge it to, say, 20% of tab width.

thx!

**Comment by Deathamns** [comment]
You don't need to move your cursor to the edge of the screen to make the menu appear. [40px is the trigger area from the left edge](https://github.com/Deathamns/Viewhance/blob/master/src/includes/viewer.js#L1969).

**Comment by rawdez** [comment]
40px is way to much precision on fullHD display

**Comment by Deathamns** [comment]
I've made [some changes](https://github.com/Deathamns/Viewhance/commit/8bcc56483adef5a2724df373ede6aa68d9b5e7ca). Now, by default, the trigger area is the area of the menu itself. I didn't want to add new option for changing it, but now you can set a transparent border for the menu via `Custom CSS` in the Options (for example `#menu { border-right: 100px solid transparent }`), which will be calculated into the trigger area.

**Comment by rawdez** [comment]
awesome, thanks!

**Comment by rawdez** [comment]
well, it doesnt work
with large border hidden menu just gets farther left:
style="display: none; left: -450px; opacity: 0;"

**Comment by Deathamns** [comment]
No, I haven't pushed it to the store yet. I usually don't publish until I have some more changes.

**Comment by rawdez** [comment]
anyway, thanks!
nice job

only thing thats missing its probably configuration export/import.
and I'm not really sure which problem is that but smartUp Gestures doesn't start gestures on images when Viewhance is active. so cant use its gestures for images.
probably has something to do with right mouseclick handling by Viewhance even when Right long-press action is disabled

**Comment by Deathamns** [comment]
I didn't want to create import/export, since there aren't many options. Personally, I only change one after installing.

I've made [another tweak](https://github.com/Deathamns/Viewhance/commit/aa63d58704d367e300a5fb5f1cb2e63583d88858), which might allow mouse gestures (but I'm not sure if it will cause any side effects in the extension).

Also, if you have other specific problems, please open separate issue reports for them.

**Comment by rawdez** [comment]
well, it totally fixed the issue for me, thank you again

**Comment by rawdez** [comment]
turns out
`the area can be increased by setting transparent borders for the menu via custom CSS`
is not the best option, because  transparent borders are not transparent for mouse clicks.
so I have to use modded Viewhance with custom menu area for this reason

**Comment by rawdez** [comment]
turns out
`the area can be increased by setting transparent borders for the menu via custom CSS`
is not the best option, because  transparent borders are not transparent for mouse clicks. its too annoying.
so I have to use modded Viewhance with custom menu area for this reason
