### ISSUE TITLE
[Feature Request] configuration export/import

### ISSUE THREAD

**Issue by rawdez** [Deathamns/Viewhance#42]
I use a lot of browsers and change a lot of settings, use custom style (CSS), custom send image to list.
its really great how customizable Viewhance is.

so it would be really nice to have ability to save full config and quickly load it to another browser.
thank you.

**Comment by Deathamns** [comment]
f1fa949.

By default it will export only the settings that you modified. If you want all of them, then the `Ctrl` key when clicking on the `Export` button. You can also hold `Shift` for pretty printing.

The page will be reloaded after successful import.
