### ISSUE TITLE
size of the menu area - episode 2

### ISSUE THREAD

**Issue by rawdez** [Deathamns/Viewhance#43]
turns out
`the area can be increased by setting transparent borders for the menu via custom CSS`
is not the best option, because  transparent borders are not transparent for mouse clicks. its too annoying.
so I have to use modded Viewhance with custom menu area for this reason

episode 1: [size of the menu area](https://github.com/Deathamns/Viewhance/issues/40)

**Comment by Deathamns** [comment]
8816204.

It is a hidden option (can be set via the import feature): `menuTriggerArea` (measured from the top left corner): [px, px] or ['%', '%'] or null for default values, which is the size of the menu itself.
