### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by happysurf** [Deathamns/Viewhance#44]
In the debug page there is this message for Viewhance:

![debug](https://user-images.githubusercontent.com/13637587/45667521-d52ef100-bb19-11e8-8076-48ce85257c9f.png)
**

This on Firefox 63beta on W10.

**Comment by Deathamns** [comment]
You can freely ignore these, as they are harmless.
The `persisntent` property is not yet supported by Firefox, the `update_url` is included for other Chromium based browsers (which Firefox simply ignores).
