### ISSUE TITLE
Alt + Left arrow doesn't trigger "Go back one page" like it should

### ISSUE THREAD

**Issue by dubhater** [Deathamns/Viewhance#45]
Normally Alt + Left arrow is the shortcut for "Go back one page" and Alt + Right arrow is the shortcut for "Go forward one page". But they don't work when Viewhance is installed and I open an image. (For example, this random image from Wikipedia: https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/St_Pancras_Railway_Station_2012-06-23.jpg/711px-St_Pancras_Railway_Station_2012-06-23.jpg )

My browser is currently Firefox 62.0 running in Arch Linux, and Viewhance is version 2018.805.1235 from August 5th.

**Comment by Deathamns** [comment]
b1204b8
