### ISSUE TITLE
Clicking anywhere on background, not only on image itself, should change zoom mode

### ISSUE THREAD

**Issue by DimkaDim** [Deathamns/Viewhance#47]
I like to open images initially in original size, and after that, in many cases, decide to zoom in to fit to viewport. Images can be very small on 4K screen, and first I have to move mouse cursor on image, to the center of the screen, then click. Aiming takes time:) It would be much more convenient if clicking on background switched zoom mode as well.

This is implemented in Enhanced Image Viewer (by Sebastian Blask) and it makes switching zoom mode quite a lot easier there.

**Comment by Deathamns** [comment]
b0ffda9

A new option has been added as `Allow mouse-clicks over the whole page`. When enabled, every mouse shortcut (click, left/right longpress, panning) should work over the whole page. Note that the cursor in order to change you still need to move it over the media.

**Comment by DimkaDim** [comment]
Thank you so much, works great.
