### ISSUE TITLE
Consider to add exact value (option) for the image adjustment options

### ISSUE THREAD

**Issue by kliop00023** [Deathamns/Viewhance#49]

**Comment by Deathamns** [comment]
What do you mean?

**Comment by kliop00023** [comment]
@Deathamns THIS:
![default](https://user-images.githubusercontent.com/7941949/48974801-cf1b3a80-f09d-11e8-8e3b-d5f8fb0e217d.png)
Change to this:
![default](https://user-images.githubusercontent.com/7941949/48974915-80bb6b00-f0a0-11e8-936e-d533066a4f2a.png)

**Comment by Deathamns** [comment]
I'm not interested in this.
