### ISSUE TITLE
[Feature Reuqest] imgur upload and more control over clicks

### ISSUE THREAD

**Issue by alivefromupstairs** [Deathamns/Viewhance#54]
- upload to imgur via Send To
- option to disable right clicking images and having them open (I trigger it way too often and never mean to use it)
- fit to width/height with double left click rather than long click would be more intuitive imo
- alt + wheel to strictly zoom as shift and drag cannot zoom you out; while switching between scrolling and zooming requires thinking. 
Thank you

**Comment by Deathamns** [comment]
* If imgur allows uploading by URL then you may be able to do that already. But I don't want to implement anything more serious than URL sending. There are many uploader extensions that already work fine.
* You mean the long-pressing on regular web-pages? That is disabled by default. See Options / Shortcuts.
* That would interfere with single clicks (which are core features, that I don't want to disable, nor making them optional), so the image would change its size twice before it would fit to width/height.
* A constant way for zooming would be nice, but I'm not sure about Alt, which in some browsers triggers the browser menu.

**Comment by Deathamns** [comment]
Commit 5e000e9 adds a new options for zooming with mouse wheel when a modifier key is being held. Not enabled by default because of browser inconsistency. Only Shift works well in Firefox, other keys are OK in Chrome.
