### ISSUE TITLE
i cannot play animated gif

### ISSUE THREAD

**Issue by Janaue** [Deathamns/Viewhance#55]
I am on firefox 56.0b12 with Viewhance	2019.321.1540 and I cannot play this gif
https://www.meteo60.fr/radars/animation-radar-france-simple.gif

when i click the play button, 
<img width="315" alt="sshot-028" src="https://user-images.githubusercontent.com/10972636/58936282-ac19c380-876f-11e9-9827-2aa6874ba04c.png">
nothing happens

**Comment by Deathamns** [comment]
What play button? The extension doesn't even have that.

**Comment by Janaue** [comment]
oh yeah the control comes from https://github.com/simonlindholm/toggle-gifs the gif plays well with his shortcut ctrl+M

**Comment by Deathamns** [comment]
ab8aa9c
