### ISSUE TITLE
SVG support [enhancement]

### ISSUE THREAD

**Issue by HatScripts** [Deathamns/Viewhance#56]
Quoting [your response from this 2016 issue](https://github.com/Deathamns/Viewhance/issues/25#issuecomment-264721902) regarding SVG support:

>It's not that simple. Supporting SVGs requires a different handling, since an SVG itself is a document. But my main reason to not support them is that they can have interactive elements (e.g., they can handle mouse events, or change their structure) where the extension would be an interference.

I would argue that the benefits of adding support for SVGs greatly outweigh the drawbacks you mentioned.

Not to mention, interactive SVGs are quite rare. Based on a sample size of 16,156 random unique SVGs I downloaded from Google:
* 16,006 (99.07%) had no interactivity
* 118 contained `<a>` elements
* 31 contained `:hover`, `:active`, `:focus`, or `:visited` css
* 1 contained `<a>` and `:hover`

Edit: If the 1% of interactive SVGs bothers you, you could also programmatically check whether the SVG contains interactivity. If it does, do nothing; otherwise, run Viewhance.

**Comment by Deathamns** [comment]
Probably we could somehow ignore interactive SVGs, but it still has to be implemented, and I am not sure if it's worth my time. SVGs don't even have concrete dimensions, also they are documents on their own, so the current code wouldn't be able to handle it.

Maybe embedding a [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) with an `img` element (for easier handling) which would load the same SVG...

**Comment by HatScripts** [comment]
> Maybe embedding a [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) with an `img` element (for easier handling) which would load the same SVG...

Just curious, but what would that do exactly?
From what I can tell, the following give more-or-less [the same results](https://codepen.io/HatScripts/pen/agqzZy), at least on an HTML document:
```
<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160">
  <foreignObject width="160" height="160">
    <img src="https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg">
  </foreignObject>
</svg>
```

```
<img src="https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg" width="160" height="160">
```

**Comment by HatScripts** [comment]
> also they are documents on their own, so the current code wouldn't be able to handle it.

Does Viewhance only work because Chromium automatically displays images (png, jpeg, etc.) within an HTML document? And the problem with SVGs is it doesn't automatically embed them as an `<img src="...">` like it does with the raster formats?

**Comment by Deathamns** [comment]
Every browser embeds media in HTML pages (you can use the web console to inspect the page, and see for yourself). Usually the media is the only content on the page. However each of them does the embed a bit differently, there are discrepancies even between versions of the same browser. For each platform I try to use clues to determine if it's a media document (for [example](https://github.com/Deathamns/Viewhance/blob/master/platform/crx/js/app.js#L149)), and then try to check when the media loads and fetch its dimensions, which happens in the `viewer.js`.
Determining if the document is an SVG would be easy, however everything else is not. Starting from determining the dimensions of the SVG. The whole code in `viewer.js` is written for handling HTML stuff.
So, with `foreignObject` we could "simulate" a HTML page, for which we already have the code. Of course, it questionable that if it will work (I don't have the time to investigate, so I can't answer now).

**Comment by Deathamns** [comment]
Support for SVGs in 8636733.
It will redirect the SVG file to an internal page, so unfortunately it will change the URL, however I've added a new option to disable SVG handling.
