### ISSUE TITLE
Doesn't work for images on 'google.com' domain [bug]

### ISSUE THREAD

**Issue by HatScripts** [Deathamns/Viewhance#58]
For some reason, Viewhance doesn't run on the following examples:
* https://www.google.com/doodles/static/sprites/sprites_v4.png
* https://www.google.com/logos/doodles/2019/50th-anniversary-of-the-moon-landing-6524862532157440.4-vacta.gif
* https://www.google.com/logos/doodles/2019/50th-anniversary-of-the-moon-landing-6524862532157440.3-2xa.gif
* https://www.google.com/logos/doodles/2015/childrens-day-2015-panama-6281767111622656-hp2x.png

Err, these ones work though, so it appears that only 'www.google.com' images are affected?
* https://developers.google.com/web/tools/chrome-devtools/javascript/imgs/pretty-print-on.jpg
* https://families.google.com/familylink/static/img/phone.png
* https://cloud.google.com/datalab/images/datalab-localhost.png
* https://www.gstatic.com/images/icons/material/apps/fonts/1x/opengraph_color_1200dp.png
* https://lh5.ggpht.com/KV-Xt9L0uaMZIezuR1f-rOeS5iVDsDev-Zb-5bEzOQYUQQEimPqva1hSZFp_=s1200

Images on the 'googleusercontent.com' domain also work fine. Examples: [1](https://lh3.googleusercontent.com/Cg8o4WUGOp092dPhsuTXo4MGHbxP9MCLfBbyXkJHItE2bIY4bEVfIy52A7VxcAwSqNQoakwBH_i9f2DULzHpaP48k9AZyjP6DdNGBGQ=s0) | [2](https://lh3.googleusercontent.com/igVPsFn2vVZgoqLY_9sBtRJTcpwQXyfrYcz5fdqT4CJv0yhOTObJZmq6kck4Rwyeasp6kyQKtfnNVCKhfFdisvxKws1LINrwNBde9w=w1440-l80-sg-rj-c0xffffff) | [3](https://lh3.googleusercontent.com/r6oFKT3BopAXit6hLx5k3PD7mu_HPjdpTQhq_mOBGlbl-diXjDqwB1WlnZMcug=s1313-p-rw) | [4](https://lh4.googleusercontent.com/pnbs5RVCWoT6J4hYJVrK7meeJCctwQXVAbNRF-G0mZmF3vGbOyL3LUqCgGvlJWD0dz4=w1200-h630-p) | [5](https://lh5.googleusercontent.com/PA54_2NgavzmE5BvTfM15F10JGwUCZyLXHzqH6n8xnv0nQNSiWW6O9X6tac=w1200-h630-p)

### **Edit:** I forgot to point out that I'm using Opera. And this bug doesn't seem to occur in Chrome. Weird.

**Comment by Deathamns** [comment]
All images opened fine for me in Opera, and in Chrome as well.
