### ISSUE TITLE
Missed menu on fastpic.ru

### ISSUE THREAD

**Issue by Rodny0** [Deathamns/Viewhance#6]
Floating menu doesn't show on fastpic images, example:
http://i70.fastpic.ru/big/2015/0826/9f/0dbfb39f852c9d2925e5ad7c5501bf9f.jpg

 Viewhance 1.0.2 + Firefox 31.7.0 ESR / Firefox 40.02

**Comment by Deathamns** [comment]
Only fastpic? And not at all, even if you refresh the image?

**Comment by Rodny0** [comment]
Some other sites that I tried are OK.
Refreshing doesn't help.

**Comment by Deathamns** [comment]
Actually fastpic images don't even load for me in a new tab, I'm being redirected to the [preview page](http://fastpic.ru/view/70/2015/0826/0dbfb39f852c9d2925e5ad7c5501bf9f.jpg.html) (even the referrer doesn't matter). Do you have any other example?

**Comment by Rodny0** [comment]
Yes, it redirected. But then click on preview image to open original one.

**Comment by Deathamns** [comment]
I see, but I can't reproduce your issue, the menu appears after moving the mouse to the cursor.

**Comment by Rodny0** [comment]
Oh, sorry to trouble you. Adblock Plus with RuAdList+EasyList subscription blocks the menu.
I turned off the following rule and all became OK:
fastpic.ru##body > div[id]:not(#mainContainer):not(#content), body > div:not([id]), body > :not(div):not(img)
