### ISSUE TITLE
Suggestion: Nearest Neighbor Scaling

### ISSUE THREAD

**Issue by walllable** [Deathamns/Viewhance#60]
Would it be possible to add an option for scaling to use nearest neighbor instead of whatever filtering is currently implemented? The current scaling can make zoomed-in pixel art rather blurry.
![image](https://user-images.githubusercontent.com/10066958/62827773-a643c280-bba4-11e9-89ba-b28ac2353316.png)

**Comment by Deathamns** [comment]
You already have that. On demand with the shortcut P, or permanently via Custom CSS: `.img #media { image-rendering: string }`, where `string` for Firefox is `crisp-edges` and for Chrome is `pixelated`.
