### ISSUE TITLE
Zoom Bug

### ISSUE THREAD

**Issue by Mike-Reddick** [Deathamns/Viewhance#63]
Using initial size mode in contain or best fit I can't use zoom like ctrl +, the only zoom which work is using the plugin loupe. Note: In natural mode ctrl zoom work! Is possible make zoom work in other modes please?

**Comment by Deathamns** [comment]
`Ctrl+` is a browser feature and it scales the whole page, including the menu for example.
If you want to use zoom only the image, then just press `+`, `-` without `Ctrl`, these are extension shortcuts.

**Comment by Mike-Reddick** [comment]
the problem is, for instance, if you use an mouse gesture to zoom in browser, if have two shortcuts, need 4 gestures, 2 to all things, 2 to images, please is possible make plugin compatible with ctrl + and - using contain or best fit?

**Comment by Deathamns** [comment]
Mouse gesture extensions probably don't send shortcuts to the page, instead they use browser APIs to change the zoom level. So, this extension wouldn't be able to intercept that.

You have a few options that you could already use for zooming with the mouse.

You can enable the "Zoom with mouse wheel" option to make wheel zooming the default.
You can on demand activate zoom-mode by holding the right mouse button over the image for a second, or you can press `Z` to swap modes.
Alternatively, you can move your cursor over the magnifier icon in the menu, and left/right click or mouse wheel over the icon.

**Comment by Mike-Reddick** [comment]
thanks,

**Comment by Mike-Reddick** [comment]
Sorry but, I'm using strokesplus (strokesplus.com) if I set + or - to an gesture, work in any page, but not in Viewhance, I tried also alt+ and alt-, same result, why? You can see it please, just Viewhance can't recognize the gesture.

**Comment by Deathamns** [comment]
Works for me. Zoom in: `acSendKeys("{ADD}")`, Zoom out: `acSendKeys("{SUBTRACT}")`.

**Comment by Mike-Reddick** [comment]
, the issue was with me :), I'm using {PLUS} instead of {ADD}, thanks so much the attention,
