### ISSUE TITLE
Viewhance removed from Chrome webstore

### ISSUE THREAD

**Issue by erasetheworld** [Deathamns/Viewhance#65]
Title. Extension no longer available on the Chrome store:
https://chrome.google.com/webstore/detail/viewhance/impppjchnpfgknmbaaghfeopcgfoilac leads to 404.

**Comment by Deathamns** [comment]
I'll copy the gist of the e-mails we exchanged:

```
Dear Developer,

Your Google Chrome item "Viewhance" with ID: impppjchnpfgknmbaaghfeopcgfoilac did not comply with our policies and was removed from the Chrome Web Store.

Your item did not comply with the following section of our Program Policies:

"Spam and Placement in the Store"

    Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
    Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
    Screenshots must demonstrate the functionality of the extension in action.
```

```
Dear Chrome Web Store Developer Support,

My extension was rejected because it violates the "Spam and Placement
in the Store" policy.

> Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
I've checked and I am unable to find anything false or misleading
information in my extension. Please be more specific.

> Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
The description does exactly that. The first sentence explains
generally what it does, and then there is a list of features. Since
I'm getting mostly good reviews, I'm sure the users understand its
functionality well.

> Screenshots must demonstrate the functionality of the extension in action.
The screenshot shows that when you open an image directly, then it has
a different background color, and it shows the floating menu (which is
mentioned in the description) with buttons for various actions (which
are explained on the support page), so again, it demonstrates what it
does.


If I am missing something, please let me know, because I don't
understand how did I violate these terms.
```

```
Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.

Here are some specific checks you can conduct to ensure your item complies with our policies.

    Descriptions must directly state/Fulfill the functionality of the app so that users can understand the extension they are adding.
    Screenshots must demonstrate the functionality of the extension in action.
```

I didn't know how to respond to the last mail, so I gave up. I feel like I was responding to a bot.

**Comment by erasetheworld** [comment]
I see, typical Google stuff as I suspected...
Back when uBlock update got rejected from webstore and someone created a reddit thread about it, there were a few Chrome devs in there so it might be worth reaching out to one of them directly:
https://www.reddit.com/r/chrome/comments/dgoymg/warning_ubo_ublock_origin_will_possibly_be/
Particularly to /u/dotproto, he posted his twitter and github in that thread.

**Comment by Deathamns** [comment]
Ping @dotproto.

**Comment by dotproto** [comment]
Hey, sorry for the late follow up. I'm not too active on GitHub so I missed the notification. 

Poking around a bit, it seems the rejection was due to the extension's listing describing functionality not present in the extension. Unfortunately I don't have specific details about what wasn't functioning as expected. I'd recommend testing to verify that all of the functionality described in the listing is working as expected. I'm also going to try to reach out to see if I can get any more info on what specifically didn't work as expected.

**Comment by Deathamns** [comment]
Hey, thanks for taking a look! Every listed (and non listed) feature works. There might be bugs, but I'm not aware of them at the moment. So, I'm still a bit confused.
I'll try to publish once more, but if I get rejected again without a clear explanation, I see no reason to continue trying.

**Comment by alivefromupstairs** [comment]
@Deathamns can you provide a CRX file in the meantime?

**Comment by Deathamns** [comment]
[This link](https://tiny.cc/Viewhance-crx) always points to the latest version. But there is a link on the homepage for the archive as well.

**Comment by alivefromupstairs** [comment]
@Deathamns
> [This link](https://tiny.cc/Viewhance-crx)

```
package is invalid: 'CRX_HEADER_INVALID'.
```

**Comment by Deathamns** [comment]
Alternatively, you can extract it and install it as an unpacked extension.

**Comment by alivefromupstairs** [comment]
From what I remember, that would give you a popup each time you open chromium.

**Comment by alivefromupstairs** [comment]
The `crx` file worked before; it's just not working now for some reason.

**Comment by Deathamns** [comment]
I have two extensions installed like that, I don't get any pop-ups.

**Comment by Jadelor** [comment]
I think the CRX_HEADER_INVALID error refers to how new Chromes require for current extension crxs to be signed with a newer tool (something about CRXv2 deprecation).

**Comment by senja1** [comment]
Can you publish it on Edge Chromium extension store?

**Comment by Ryonez** [comment]
Need to be a little careful with URL shortners, when they die, it's gone:

![image](https://user-images.githubusercontent.com/16157130/79717421-b4e69a00-832d-11ea-831f-6d88cf07ae32.png)

Is there any potential for this to come back?

**Comment by Deathamns** [comment]
Actually I deleted the short link, I am planning to move away from it.
[This is the main page](https://github.com/Deathamns/Viewhance), and you can find the archive link there (beside the Changelog) for different builds.

Regarding CWS, I've tried to send it again. The last time they were complaining about the description (see my first comment in this thread), so I removed everything and left one or two sentences there to state what the extension does. Then I got the same automated "Spam and Placement in the Store" reply. Again, I have no idea what their problem is, because I see none. I won't be trying anymore.

**Comment by 1024mb** [comment]
> Actually I deleted the short link, I am planning to move away from it.
> [This is the main page](https://github.com/Deathamns/Viewhance), and you can find the archive link there (beside the Changelog) for different builds.
> 
> Regarding CWS, I've tried to send it again. The last time they were complaining about the description (see my first comment in this thread), so I removed everything and left one or two sentences there to state what the extension does. Then I got the same automated "Spam and Placement in the Store" reply. Again, I have no idea what their problem is, because I see none. I won't be trying anymore.

Couldn't you make a release (on Github) so we can update and install the extension manually?

**Comment by Deathamns** [comment]
Follow the [Archive](https://drive.google.com/drive/folders/0Bx8fnUCX4W2IOTdESEFoM3luS1U) link on the [homepage](https://deathamns.github.io/Viewhance/), there you can find packed versions for each platform. Or build it for yourself.

**Comment by 1024mb** [comment]
@Deathamns I didn't saw that link, thanks.

**Comment by seascape** [comment]
Thank you for this and Imagus. Both great.

I wanted to show Viewhance to a Chrome user but the Archive link (Google Drive) is 404ing now?
