### ISSUE TITLE
Issue with file named "file .png.pdf"

### ISSUE THREAD

**Issue by maverick74** [Deathamns/Viewhance#66]
I'm having problems with a file named "file .png.pdf".

The creator of the file has made a mistake and created it with "two extensions".
The problem is that viewhence is, naturally assuming it is a PNG file, while the file is actually a PDF.
Not only it can't read it, it disables FF's built-in pdf reader.

**Comment by Deathamns** [comment]
Can you link the file?

**Comment by maverick74** [comment]
Hi. Thanks for the quick reply.

I cannot send you the "real" file as it is an invoice with actual personal data on it, but I'll try to replicate the problem and will get back to you asap.

**Comment by Deathamns** [comment]
I take a quick look, and immediately noticed [this line](https://github.com/Deathamns/Viewhance/blob/master/platform/crx/js/app_bg.js#L149).
So, if you disable the extension and try open the pdf file, and your browser offers you the save dialog, then probably this is the issue.
Or if you have the possibility to test it with a browser that still uses the XUL platform, then you can install v2019.1119.1805 from [here](https://drive.google.com/drive/folders/0Bx8fnUCX4W2IVU5Dd08yUU5VNUE), and if it works, then we know the issue.

**Comment by Deathamns** [comment]
273d1ad could be a potential fix for your issue.

**Comment by maverick74** [comment]
i tried to replicate the problem but so far was not able to.
Where can i try a version with the fix?

**Comment by Deathamns** [comment]
For now, you have to build it for yourself.

**Comment by maverick74** [comment]
oh... i'll have to wait then ;)

It seems it was looking for the first string with a extension on it... while the last extension is the one that counts... or am i missing the interpretation of the problem?

**Comment by Deathamns** [comment]
Yeah, it was something like that.

**Comment by Deathamns** [comment]
I've published a new version. Can you confirm if your issue has been solved?

**Comment by maverick74** [comment]
Yes!!! It's Working like a charm now!!!

Thank you so much!!!

I wish you happy holidays :)
