### ISSUE TITLE
Viewhance Installation and Packing Issues

### ISSUE THREAD

**Issue by Bamajon1974** [Deathamns/Viewhance#68]
What is the best way to install the Viewhance extension manually? 

I retrieved Viewhance.crx (dated April 2, 2020) from https://drive.google.com/drive/folders/0Bx8fnUCX4W2IOTdESEFoM3luS1U and saved to my download folder.

I am assuming that viewhance-2020.402.1540-crx.crx is the same as above, right? 

I dragged and dropped Viewhance.crx to chrome://extensions/ with Developer mode on and got this error message: Package is invalid: "CRX_Header_Invalid". Why does this happen? 

I used 7-Zip to extract the Viewhance.crx (%download%/Viewhance folder) and installed by choosing Viewhance folder from the %download% directory using "Load Unpacked" managed to successfully install the extension. However, when I restart Chrome, I get this message "Disable Developer Mode Extensions". I added the latest Chrome group policy extensions to gpedit.msc and whitelisted the Viewhance extension ID and the message still appears. Why does this happen? 

I also tried to repack the Viewhance extension that I extracted from 7-Zip above to create a new crx file and when I dragged the new packed crx file to chrome://extensions, the Viewhance was corrupted and repair does nothing. 

When I repack the extension, do I pack the files extracted by 7-Zip from the %download%/Viewhance folder above or do I repack them from another directory? 

When I drag and drop a crx file, do I need the key file that is generated when you pack the extension? 

Thanks!

**Comment by Deathamns** [comment]
For Chrome, I simply build the extension, then load it as unpacked. I don't remember what have I changed to not show that warning dialog, but I never see it.
Maybe because I have the [Developer Edition](https://www.google.com/chrome/dev/).

**Comment by Bamajon1974** [comment]
How do you build the extensions? I am not a coder so I am not familiar with
anything but installing extensions.

Also, the CRX_Header_Invalid apparently means the extension needs to be
repacked in CRX3 format.

I read extensively about the warning dialog box but it only appears on
stable builds of Chrome.

Thanks!

**Comment by Deathamns** [comment]
Extracting the built `crx` file has the same effect as building, but if you're adventurous, you need [Python](https://www.python.org/downloads/), download the source, then simply in the command line run `python build.py crx` under the extension's folder, the output will be in `build/crx` (which you can install).

I'll look into the CRX_Header_Invalid issue.

**Comment by Bamajon1974** [comment]
Got it. I was able to successfully install the extension by extracting the
crx file. When you install extensions by dragging crx files over
chrome://extensions window, do you know where these extensions are
extracted and located? I noticed that if you extract the crx file in, say,
the download folder and install from the download folder and then remove
the files from the download folder after installation, then the extension
does not work. Apparently Chrome looks for that extension to whatever
directory you install from. I found out that extensions installed from the
Chrome store are stored in C:\Documents and Settings\username\Local
Settings\Application Data\Google\Chrome\User Data\Default\Extensions but if
I try to move the Viewhance extracted files to this folder, they are
deleted after Chrome is restarted. So I guess if I have to install the
extension from extracted CRX file, then where should I extract the crx file
to?

Thanks!

**Comment by Deathamns** [comment]
`\User Data\Default\Extensions` sounds right. But Chrome probably doesn't allow extensions there that were not installed through the browser.
You can install unpacked extension from arbitrary locations, however the folder must stay there, you can't delete it.

**Comment by Bamajon1974** [comment]
Exactly. That is why I wanted to try to install via the CRX file.

When I loaded the unpacked extension, then repacked and tried to drag and
drop the new crx file onto the chrome://extensions window, the extension
installed but was corrupted and couldn't be repaired. Do you have the same
issue too?

**Comment by Deathamns** [comment]
Yes, I can't package it with Chrome either. Also I tried to use the script I found on the net to package the extension with CRX3 format, but they resulted in the same error as well.

**Comment by Bamajon1974** [comment]
Ugh Google. I can install the extension manually and deal with the
unsupported extension notice until a solution is found. Where do you
recommend installing the extension?
Thanks!

**Comment by Deathamns** [comment]
It doesn't matter where. Put somewhere where it's not in your way.

**Comment by Bamajon1974** [comment]
Will do. Let me know if you get the invalid manifest issue worked out.

Thanks, Jon

**Comment by dnknn** [comment]
Or you can also try [🌌CentBrowserᐝ](http://centbrowser.com/) (fork of Chromium) , 
It can directly drag-drop the `.crx` file into the browser for installation.

`CentBrowser` will not significantly change the `Chromium` kernel, 
it is just an enhancement on the basis of `Chrome` that the `extension` cannot do or `extension` is difficult to do.
It will not disappoint you :)

**Comment by Paulaob79** [comment]
Had to do the same, unpack the crx file with 7zip to be able to install it unpacked.

Chrome still won't install the crx and give me "CRX_Header_Invalid" message.

**Comment by Bamajon1974** [comment]
I can confirm that the same "CRX_Header_Invalid" message" also appears when dragging the crx file to the extensions page in Edge as well. However, I extracted the contents of the crx file and copied to a folder C:\Users\(user name)\AppData\Local\Microsoft\Edge\User Data\Default\Unsigned Extensions\Viewhance and loaded the unpacked extension in Edge v86 and don't get the persistent warning about running non-approved extensions.

**Comment by Bamajon1974** [comment]
I found a way to remove the "disable developer extensions" warning in Edge/Chrome. Please refer to this link. I just tried it out and it works. https://techjourney.net/remove-disable-developer-mode-extensions-warning-popup-in-chrome-edge/
Now there is no need to worry about getting Viewhance approved by the store and having that nagging developer mode extension pop up everytime the browser starts.
