### ISSUE TITLE
Feature Request: Drag image anywhere

### ISSUE THREAD

**Issue by gms9rc** [Deathamns/Viewhance#69]
Currently images can only be positioned in the top left corner or centered. I would like to be able to drag an image to any location including past the edges of the viewport. The reason I want this feature is because I span windows across multiple monitors and sometimes part of the image is blocked by the bezel gap. If it were possible to drag the image off-center then I could see that part of the image. The drawing below shows examples of what I want to be able to do.
![viewhance](https://user-images.githubusercontent.com/3283770/86519044-948e8d80-bdfc-11ea-9724-aa0efd742bc5.png)

**Comment by Deathamns** [comment]
Currently image panning happens simply by moving the scrollbars (so scrolling the page). Your request would require a different approach, which probably needs a lot of rewrite.

**Comment by gms9rc** [comment]
I will try to code it myself when I get some extra time soon hopefully. I was planning to replace any scrolling requests with an adjustment to the top left corner of the image. Is that how you would approach it?

**Comment by Deathamns** [comment]
I already have made [attempts](https://github.com/Deathamns/Viewhance/files/4990774/smooth-wheel.zip) to implement a different feature (smooth zooming), which requires the same changes, but then I realized that I have to re-implement scrollbars, and backed off. Also, panning wasn't that smooth like with scrollbars, neither older browsers supported the technique. So, I had a few reasons, not to finish it.

**Comment by gms9rc** [comment]
Sorry for the delayed response. I gave up and forgot to tell you. You can close this issue now unless you want to take it further.
