### ISSUE TITLE
ℹ Show image-info 

### ISSUE THREAD

**Issue by dnknn** [Deathamns/Viewhance#71]
### Can show `image-info` to be displayed in the upper right corner ❓	
At the same time, also a `shortcut `corresponding to it, which can be temporarily hidden.

<br>

  ⓘAttributes | ⓘAttribute value  | description
:---: |--- |--- |
original WxH:  |   1428x756   | (original width & height)
current  WxH:  |   750x256   | (width&height of zoom)
Type:   |     .jpg/.jpeg/.png/.svg/.webp/.gif/...   | (Picture format)
Size:    |    78㎅  / 2.5㎆            |      (Picture size)
current Zoom :   |   60%                 |         (real-time dynamic  display percent of the original size)

![208_09034743](https://user-images.githubusercontent.com/10995302/89718671-16bd3380-d9f3-11ea-961f-197de8a7c28f.png)

![pic-info](https://user-images.githubusercontent.com/10995302/89719667-4cffb080-d9fd-11ea-965b-edc34e4ae178.gif)

----
Specific reference to this 🐵Tampermonkey UserScript
-  ### https://greasyfork.org/scripts/16403
> This script is also a separate tab for independent image. it has 2 useful functions :

&emsp; &emsp; 💪Can show image attribute info 
&emsp; &emsp; 💪Can use <kbd>Esc</kbd> to quickly close the image tab

> `Esc` 		&emsp;&emsp;quickly close tab
`Shift` 		&emsp;temporarily close or display picture information
`Enter` 		&emsp;to switch the image source size, or switch to automatic zoom size

**Comment by Deathamns** [comment]
You have `Image information` which is applied to the tab title. I'm not interested in adding overlays. Though, I can add a new variable for the content-type (6f44033).

**Comment by dnknn** [comment]
Good understanding, thank you.
