### ISSUE TITLE
invalid for  Force inlining

### ISSUE THREAD

**Issue by dnknn** [Deathamns/Viewhance#72]
![image](https://user-images.githubusercontent.com/10995302/89735341-69026100-da94-11ea-987f-a25bfa0f366c.png)

But it is invalid, Clicking to open always pops up the download dialog, 
and cannot be opened independently in a new tab. 
for example  
https://picb.zhimg.com/v2-2ac80924dbaf17ecd593663a0e9d4e3f.jpg
https://picb.zhimg.com/v2-fd2a465e72f4f434eea6c9f6addc4cfb.jpg
https://pic4.zhimg.com/v2-2eeb82ded3163f8ff8a467c1de2f0625.jpg

**Comment by Deathamns** [comment]
45a7554. Only for this particular case. If there are no file extensions in the URL, I can't do much.

**Comment by dnknn** [comment]
Thank you very much
