### ISSUE TITLE
Can you optimize: hovering under iframe for `Imagus`

### ISSUE THREAD

**Issue by dnknn** [Deathamns/Viewhance#73]
Hi @Deathamns ! sorry, I don't know where to report bug for Imagus, so let's post it here .:)
`Imagus` is perfect&powerful, under the normal framework especially. Except  the following 2 💥 problem/bug  in the `iframe`.

Because have animated gif , so recommend 2 extensions about GIF control. [GIF Player](https://chrome.google.com/webstore/detail/alhgepkoeafgfdfonlclgphnedliblpf) or [GIF Scrubber](https://chrome.google.com/webstore/detail/gbdacbnhlfdlllckelpdkgeklfjfgcmp)

----
### &emsp;&emsp;&emsp;&emsp;But in the `iframe` frame, the opposite is true.
---
> ❖Win10¹⁹⁰³  ֎Chrome⁸⁰ &emsp;&emsp; any version of Imagus

1. ## 💥 When hovering on the picture, infinite loop flashing, instead of displaying the big pic normally.
It keeps flickering during hovering, and it can't be a perfect hovering like a non-iframe.
![Infinite flashing](https://user-images.githubusercontent.com/10995302/89787696-7ed55c00-db50-11ea-8ce4-1c11ab97aa0e.gif)
Not only will it cause visual disturbance, but it is also difficult for Imagos to trigger the hover of the big picture.
&nbsp;

2. ## 💥 On some iframe, `Imagus` doesn't working at all, or difficult to work properly. 
![iframe](https://user-images.githubusercontent.com/10995302/89789890-cb6e6680-db53-11ea-929a-8903afe269df.gif)
This gif demo about 2 problems with iframe.
On some iframe, `Imagus` **doesn't working** at all, finally I found that there is a manual fix method:
Reload the page, and then **click** the place **outside the iframe** with the mouse in advance, Only then can let `Imagus` working.

---

The two problems mentioned above have nothing to do with the `rules`.
The `<img>` element itself is a big picture, or it is redirected to a big picture.
For detailed experience, you can open this page to testing under `iframe`.
https://note.youdao.com/coshare/index.html?token=ADA218DA59644238935FD7FD83AE7028&gid=115094259

**Comment by Deathamns** [comment]
I will later delete this post, because for Imagus you should post things here: https://www.reddit.com/r/imagus/
I did improve frame handling in my dev version by the way.

Side note: you can play animated images (GIF, APNG, WEBP) in Viewhance as well (the frame extraction feature).

**Comment by dnknn** [comment]
> I will later delete this post, because for Imagus you should post things here: https://reddit.com/r/imagus/

I seem don’t know how to use reddit.com, and no login account.
sorry...

> Side note: you can play animated images (GIF, APNG, WEBP) in Viewhance as well (the frame extraction feature).
Cannot control play/pause with `Space`

**Comment by Deathamns** [comment]
iframe

**Comment by dnknn** [comment]
> iframe

beautiful + nice + great !
