### ISSUE TITLE
A good suggestion to `Search all engines`

### ISSUE THREAD

**Issue by dnknn** [Deathamns/Viewhance#74]
A picture tells everything :
![209_21113551](https://user-images.githubusercontent.com/10995302/93731225-acf19580-fbfe-11ea-94fc-da0806044fd3.png)

- Current issue: Only search one engine separately

- Expected behavior: Search all or multiple at the same time

---
Image search is not as accurate as text search. The image search of each engine is almost completely different, so using multiple engines at the same time can greatly improve search results.

![209_21114111](https://user-images.githubusercontent.com/10995302/93731399-5a64a900-fbff-11ea-95d7-4e5b4d6b6bb6.png)

But the plus sign ✚ has no effect in `Viewhance` 

---
※reference

![209_21114829](https://user-images.githubusercontent.com/10995302/93731619-61d88200-fc00-11ea-964b-7a1ccc48052c.png)
https://chrome.google.com/webstore/detail/cnojnbdhbhnkbcieeekonklommdnndci
https://github.com/dessant/search-by-image

**Comment by Deathamns** [comment]
That would make sense if it was an image search feature, but it is not. You can send the url anywhere (see the qrcode reader for example). You can use the middle click to open them quickly.

Also, I'm thinking about abandoning this project, so probably I won't be adding anything new.

**Comment by dnknn** [comment]
> You can use the middle click to open them quickly.

yes, pressing Ctrl+click is also can do it. It doesn't matter, it's not a big problem.


> Also, I'm thinking about abandoning this project,

Why you want to give up this extension ?
`Viewhance` is very good and easy to use, it is a great independent-tab-pic-viewer.

**Comment by Deathamns** [comment]
> Why you want to give up this extension ?

I was thinking about handling media tabs too with Imagus (simply auto-activate it there), so I don't have to maintain two separate code bases.

**Comment by dnknn** [comment]
> I was thinking about handling media tabs too with Imagus (simply auto-activate it there), so I don't have to maintain two separate code bases.

Well, I see. Viewhance and Imagos are combined, if there is no problem, and performance is not affected, it is also possible.

Finally, I would like to ask if there is a new beta version of Imagus? Regarding improving `iframe`

**Comment by Deathamns** [comment]
I don't have anything, and unfortunately I won't for a while.

**Comment by dnknn** [comment]
Okay,Thanks♪(･ω･)ﾉ ,  looking forward to the next update on improving `iframe`
