### ISSUE TITLE
[Feature Request] Cycle page backgrounds

### ISSUE THREAD

**Issue by G-r3x** [Deathamns/Viewhance#78]
Thanks, one of the most useful add-ons for Firefox.
I'd like if there was a shortcut to cycle page backgrounds like the B shortcut does for transparent images.
Actually the only way to do this is manually change CSS every time.

**Comment by Deathamns** [comment]
I don't see the use case for that. Image background changing is good for transparent images, but the background of the whole page is basically your theme. I don't know why would you change that on demand.

**Comment by Deathamns** [comment]
I've added `Ctrl+Alt+B` to switch between media and page background cycling. 4843509
I probably don't want to go further than that.
