### ISSUE TITLE
[FR] Floating menu over the top-left image corner

### ISSUE THREAD

**Issue by eadmaster** [Deathamns/Viewhance#79]
when opening small images i have to move the mouse a lot to reach the floating menu.
Can you add an option to always showing over the image itself?

**Comment by dnknn** [comment]
@eadmaster I personally disagree with your opinion, but maybe you can implement it yourself :

```css
	  #menu {
		  ....your custom style.....
	  }
```

**Comment by eadmaster** [comment]
ok, i'll try but i won't send a PR with an user option for that.

The file to change is [this](https://github.com/Deathamns/Viewhance/blob/master/src/css/options.css), right?

**Comment by dnknn** [comment]
> The file to change is [this](https://github.com/Deathamns/Viewhance/blob/master/src/css/options.css?rgh-link-date=2021-05-06T12%3A29%3A44Z), right?

no... 
chrome-extension://impppjchnpfgknmbaaghfeopcgfoilac/options.html

**Comment by eadmaster** [comment]
oh i see now, it's in the addon settings :-)

**Comment by eadmaster** [comment]
to have the floating menu in the top-left image corner which Css  properties should i set?
(sorry, i'm a backend guy :-))

**Comment by dnknn** [comment]
```css
#menu#menu#menu	{
		display: inline-flex!important;
		opacity:1!important;
		left:22% !important;  /*For example:...*/
		/*👆 Absolute position ! */
}
```

> `CSS` is also very powerful, but for this kind of demand scenario you want, you need to judge the position of the image, and CSS is estimated to be unable to meet your needs.
> CSS can change the position or appearance, etc., but if it is a dynamic judgment of complex logic, `JavaScript` can be used.

The scene you need is complicated, for example, zooming out can zoom in/out, for example, the image can also be large/small.

**Comment by Deathamns** [comment]
The implementation would be unnecessary complicated and inconsistent (different sizes, rotated images...). The current way is fine.
