### ISSUE TITLE
"Touchpad scrolling too fast" on mac

### ISSUE THREAD

**Issue by wickles** [Deathamns/Viewhance#8]
I have an issue where it scrolls too fast by default on my mac. I remember I was able to fix this before by changing the custom CSS but I can't for the life of me find the solution again on the web. I think the solution was posted before on the chrome webstore but it appears to have been wiped and I can only find [this record](https://www.chromebeat.com/app/viewhance/ijabcgpjcbpphfagcaknnlcfeodbnkgp/support) of just the issue description archived on chromebeat.com. 

> Subject: Touchpad scrolling too fast
> Comment: If you scroll with the two-finger-swipe gesture on a MacBook, the image flies by at a speed much higher than e.g. a website would. Scrolling through a picture 5000px tall takes a movement of fingers of about 5 millimeters, which makes this way of scrolling unusable.

Please let me know if there is a way to fix the issue. Thanks!

**Comment by wickles** [comment]
Nevermind, I fixed it by changing

>body { background: silver; overflow: **hidden**; }

to 

>body { background: silver; overflow: **auto**; }

after consulting the help popup which shows

>body {
 background: #f3f3f5; /* Any valid background property (color, url(), gradient...). */
 overflow: hidden; /* Hides the scrollbars. To show them, change "hidden" to "auto". */
}

Hope this helps anyone else scratching their head out there :)

**Comment by Deathamns** [comment]
Just for the record, you can simply remove the ` overflow: hidden;` part, since `auto` is the default.

But, there are still cases where this won't help. For example, there is a feature for large images, mostly[wide](http://www.myhimalayas.com/namtso/image/large/panorama_lalungla_wide_shishapangma_small.jpg) (images](http://www.trentwindsurfing.org.uk/wp-content/uploads/2011/08/GottBayPanorama.jpg), where you can move your cursor to the bottom left part of the page and scroll there to move the image horizontally, or when the image doesn't fit the window height, then you can scroll anywhere on the page and the image will move horizontally.
I guess you will still have the issue with these cases.

**Comment by Deathamns** [comment]
[Here](https://0a723c54be9508c4ffa3b67d7d2ce5d94c6d3be0.googledrive.com/host/0Bx8fnUCX4W2IOTdESEFoM3luS1U/wheeltest.html)'s a testpage. You can wheel over the page, and it will record events in a 300ms frame (so in a moderately fast scroll).

Copy and paste here one or two results when you do a rapid scroll (scroll time should be under 70), and then do one or two longer moderate wheeling (scroll time should be over 190).

Here's mine for a mouse wheel:
```
-- quick gesture --
scroll time: 55
number of events: 6
delta: pixel,166.66665649414062
events with same timestamp: {}
diffs: 11,8,12,9,15
min diff: 8
max diff: 15

-- moderate gesture --
scroll time: 211
number of events: 12
delta: pixel,166.66665649414062
events with same timestamp: {}
diffs: 32,27,21,15,12,17,15,12,14,18,28
min diff: 12
max diff: 32
```

**Comment by Deathamns** [comment]
[Related discussion](https://www.reddit.com/r/imagus/comments/3k9t3v/scrolling_through_albums_far_too_sensitive_on/).

**Comment by wickles** [comment]
It's not working as well anymore. Auto is still better than hidden but doesn't scroll smoothly (or at all, vertically) anymore.

**Comment by wickles** [comment]
Hey, sorry I never got back about the test page before, I must have been busy at the time and forgotten about it. Anyway, here are my results. 

PC first (will come back and edit from my mac): 

> -- quick gesture --
    scroll time: 78.8299999999872
    number of events: 7
    delta: pixel,100
    events with same timestamp: {}
    diffs: 17.47500000000582,12.619999999995343,8.884999999994761,8.345000000001164,9.794999999998254,21.70999999999185
    min diff: 8.345000000001164
    max diff: 21.70999999999185

> -- moderate gesture -- 
    scroll time: 210.4299999999348
    number of events: 5
    delta: pixel,100
    events with same timestamp: {}
    diffs: 42.12499999994179,33.05999999999767,43.68500000005588,91.55999999993946
    min diff: 33.05999999999767
    max diff: 91.55999999993946

**Comment by wickles** [comment]
Well it turns out to be a little difficult to get consistent results on my macbook's trackpad. It registers multiple scrolls for every swipe, mostly with high scroll times (300+). Have to swipe very lightly and quickly to get one result at a time. Here are some examples. 

> -- light, quick scroll --
    scroll time: 128.67500000001746
    number of events: 15
    delta: pixel,0
    events with same timestamp: {"218790.00000000003":2}
    diffs: 32.49499999999534,8.195000000006985,7.725000000005821,7.705000000016298,8.014999999984866,8.410000000003492,7.7149999999965075,8.34499999997206,7.975000000034925,7.845000000001164,8.23499999998603,8.080000000016298,7.934999999997672,0
    min diff: 0
    max diff: 32.49499999999534

> -- quick 'normal' scroll (final result) --
    scroll time: 288.46500000001106
    number of events: 28
    delta: pixel,0
    events with same timestamp: {"67287.59000000001":2}
    diffs: 23.760000000009313,7.6599999999889405,8.310000000012224,8.154999999984284,7.81500000001688,7.9799999999959255,7.849999999991269,8.279999999998836,8.000000000014552,8.264999999999418,7.8950000000040745,7.649999999994179,8.669999999998254,7.879999999990105,8.10000000000582,7.985000000000582,7.670000000012806,8.204999999987194,8.169999999998254,7.970000000001164,7.875,7.82499999999709,8.279999999998836,8.35000000000582,55.75999999999476,24.105000000010477,0
    min diff: 0
    max diff: 55.75999999999476

**Comment by Deathamns** [comment]
Yes, we kind of figured it out with a reddit user If you've read the related discussion that I linked above. Unfortunately, I don't know any way to know the difference between a real and a spurious wheel event.

**Comment by Deathamns** [comment]
Closing, as this is more like a platform issue, and there's no possible JavaScript solution for it.
