### ISSUE TITLE
Frame extraction not working on github gifs?

### ISSUE THREAD

**Issue by iamhammer** [Deathamns/Viewhance#81]
Find the animated gifs at this
https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour
I cannot extract frames. I've tried downloading the file locally and using Viewhance, I've created other gifs with the same resolution and larger filesizes and they all work. I do not know what it is about the gif from the above link, but I cannot extract the frames.

**Comment by Deathamns** [comment]
Those seem to be invalid GIF files. They have an empty comment block extension at the end of the file.
Loosing the parser a bit helps (but only in this case) 1d502ef.
