### ISSUE TITLE
doesn't work in Firefox 95.0.2 with videos anymore 

### ISSUE THREAD

**Issue by rawdez** [Deathamns/Viewhance#83]
stopped working
link example 
`https://scontent.cdninstagram.com/o1/v/t16/f1/m51/7E48E5734ED5EFA70CB800D6095871B0_video_dashinit.mp4?efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uNzIwLnN0b3J5LmJhc2VsaW5lIn0&_nc_ht=instagram.fdnk1-4.fna.fbcdn.net&_nc_cat=109&vs=642673363590122_1574678586&_nc_vs=HBksFQIYRGlnX3hwdl9wZXJtYW5lbnQvN0U0OEU1NzM0RUQ1RUZBNzBDQjgwMEQ2MDk1ODcxQjBfdmlkZW9fZGFzaGluaXQubXA0FQACyAEAFQAYJEdOaTNMeEJ4LUxCUnB2b0hBSEIxSzAwTUUzRXRicGt3QUFBRhUCAsgBACgAGAAbAYgHdXNlX29pbAExFQAAJrbI56bdkMY%2FFQIoAkMzLBdAJBDlYEGJNxgSZGFzaF9iYXNlbGluZV8xX3YxEQB16AcA&_nc_rid=4d6a50f0f3&ccb=9-4&oe=61DD9BC3&oh=00_AT_EFVwjYvTvlqLNs5Gg5ZOEiz_uMJwFkcXJpK9kWjZqpw&_nc_sid=643ae9`

**Comment by Deathamns** [comment]
That is not a valid video file.
If you check the video [example](https://upload.wikimedia.org/wikipedia/commons/d/de/Hdr_time_lapse_montage.ogv) from the README, it still works fine. At least in Nightly.

**Comment by rawdez** [comment]
nope, I use Firefox 96.0.3 (64-bit) EME-free (DRM-support disabled),  example from the README doesn't work. Viewhance version 2020.913.1025
regarding instagram links not being a valid video file - their links die very fast. you can open any video from someones stories and it'd be just that - an .mp4 file with a bunch of crap attached to its end for security reasons, works for some time then dies.
that said that crap attached shouldn't be the problem because even example from the README doesn't work.

**Comment by Deathamns** [comment]
[FF96.0.3 DRM disabled](https://user-images.githubusercontent.com/5853030/151659998-f09067cf-3932-4536-b4d8-f513ea19d0f8.png). Still works fine.

**Comment by rawdez** [comment]
i mean video works, but where is Viewhance controls like zoom/rotate/filter etc.?
I used to be able to zoom video with mouse scroll wheel and rotate it with  Viewhance menu

**Comment by Deathamns** [comment]
[Simply move your cursor to the top left corner](https://user-images.githubusercontent.com/5853030/151660505-c13d4e81-5010-4e36-bfde-117af2731e21.png).

**Comment by rawdez** [comment]
well, i found out what kills it. if NoScript is an active add-on then Viewhance doesn't work with videos, even if all restrictions are disabled globally. 
anything you can do about that?

**Comment by Deathamns** [comment]
Sorry, I don't really want to fight an extension that cripples pages to such extent.

**Comment by rawdez** [comment]
well, for anyone who are reading this to find a solution for the same problem - I've installed an old version of NoScript 11.2.11 from here addons.mozilla.org/en-US/firefox/addon/noscript/versions/ and now everything works just as it used to.

**Comment by hackademix** [comment]
This should be fixed in [NoScript 11.3.3rc5:](https://noscript.net/getit#devel)

v 11.3.3rc5
===
x Play nice with  the Viewhance extension
x Avoid synchronous fetching for remote embedding documents
x Fixed typo in UI context dropdown initial selection
