### ISSUE TITLE
Can popup time be set?

### ISSUE THREAD

**Issue by minshifu** [Deathamns/Viewhance#84]
Thank you for your great addon! Can popup time be set? That is, can the popup image keeps showing for a certain time period even when mouse is outside the popup image?

Thank you and best regards!

**Comment by Deathamns** [comment]
What popup?

**Comment by minshifu** [comment]
> What popup?
> 
> Maybe you are confusing this with my other extension? There you can press Z or Enter to pin the pop-up.

Sorry I confused it with Imagus

**Comment by Deathamns** [comment]
No.
