### ISSUE TITLE
Windows scaling scales original image size

### ISSUE THREAD

**Issue by Dediggefedde** [Deathamns/Viewhance#85]
When I put my windows setting for scaling to 200% on my tablet, the "original size" in Viewhance is also double as high/wide. My firefox-zoom is set to 100%.

I use Windows10 v21H2 on a Surface Pro 1796 (gen5) and Firefox v98.0.1 portable with Viewhance v2020.913.1025.

**Comment by Deathamns** [comment]
See the FAQ / Hidden options / `scaling`.
In brief; you can try importing this `{"scaling": "*"}`.

**Comment by Dediggefedde** [comment]
Thanks, that's working well!
It's a pretty hidden option... Of course, I didn't fully read the FAQ, though. ^^'
