### ISSUE TITLE
Can't zoom, or access menu on videos orientated by meta-tags

### ISSUE THREAD

**Issue by kr4ssi** [Deathamns/Viewhance#86]
Example: https://vid.pr0gramm.com/2022/03/24/1da19fa54bfcaa76.mp4

If I zoom before the video has finished loading, it works, strangely enough.

**Comment by Deathamns** [comment]
Browser: Firefox.
Steps to reproduce: copy link, open a new tab, paste and go.

In this case the browser doesn't fire the 'loadedmetadata' event on the media, so the extension cannot finish its initialization. Fixed in 137029a.
