### ISSUE TITLE
Stopped working in Firefox 101.0a1 on Mac

### ISSUE THREAD

**Issue by gsbabil** [Deathamns/Viewhance#87]
### Issue Details

- Viewhance stopped working in the most recent version of Firefox Nightly _e.g._ `101.0a1`.
    - The addon is installed and available via `about:addons`, preferences can be changed, _etc._
    - But the floating menu and the rest of the functionality stopped appearing/working in the image/video only tabs.

#### Firefox Version

- Version: 101.0a1 (2022-04-17) (64-bit)

#### OS Version

- ProductName:	macOS
- ProductVersion:	12.3.1
- BuildVersion:	21E258

**Comment by Deathamns** [comment]
2884f9e.

**Comment by gsbabil** [comment]
Hi @Deathamns, 

Thanks a lot for fixing it so quickly! I appreciate it very much.
