### ISSUE TITLE
Feature Request - seperate sizing mode for movies/animation

### ISSUE THREAD

**Issue by Etheral** [Deathamns/Viewhance#89]
Hi great plugin/extension.

I generally don't mind scrolling in 1 direction with static images so have the initial sizing mode set to best fit
however for videos/animations I would prefer to have it contain the video.

would it be possible to add another option to use for animated files? I realise for gifs or animated png's it might be difficult but even if it was just for movie that would be nice.

**Comment by Deathamns** [comment]
I've disabled default best fit for videos, makes sense to always fit them to the viewport.
